name: Commit Message Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches:          # Run on all branches
      - '**'

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v3

        - name: Get PR Commits
          id: get-pr-commits
          uses: tim-actions/get-pr-commits@master
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Check Commit Messages
          uses: tim-actions/commit-message-checker-with-regex@v0.3.1
          with:
            commits: ${{ steps.get-pr-commits.outputs.commits }}
            pattern: '^(feat|fix|docs|style|refactor|perf|test|chore|hotfix): .+ \[I-\d+\]$'
            error: 'Invalid commit message format. Required format: ACTION: message [I-<issue number>]'