name: Commit Message Validation

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches:
      - '**'

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get PR Commits
        id: get-pr-commits
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Invalid Commit Messages
        run: |
          echo "Checking for invalid commit messages..."
          commits='${{ steps.get-pr-commits.outputs.commits }}'
          pattern='^(feat|fix|docs|test|chore)#\d+\s*:\s*.+$'
          invalids=$(echo "$commits" | jq -r '.[] | select(.message | test("'"$pattern"'" ; "i") | not) | "\(.sha): \(.message)"')
          if [[ -n "$invalids" ]]; then
            echo "Invalid commit messages found:"
            echo "$invalids"
            exit 1
          else
            echo "All commit messages are valid."
          fi